---
- hosts: all
  name: Prepares a SELinux workshop
  become: yes
  connection: local
  tasks:

  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    with_items:
      - firewalld
      - audit
      - python3-libselinux
      - python3-libsemanage
      - policycoreutils-python-utils
      - python3-policycoreutils
      - policycoreutils-devel
      - policycoreutils-newrole
      - selinux-policy-doc
      - setroubleshoot-server
      - setools-console
      - make
      - gcc-c++
      - libcurl-devel.x86_64
      - rpm-build
      - rhel-system-roles

  - name: Ensure SELinux is in enforcing mode
    vars:
      selinux_policy: targeted
      selinux_state: enforcing
    include_role:
      name: redhat.rhel_system_roles.selinux

  - name: Create dir with working files
    ansible.builtin.file:
      path: /root/selinuxlab
      state: directory
      mode: 0755

  - name: Ensure SELinux test app source is on the system
    ansible.builtin.copy:
      src: files/testapp.c
      dest: /root/selinuxlab
      mode: 0755

  - name: Ensure Makefile for the test app is copied to the system
    ansible.builtin.copy:
      src: files/Makefile
      dest: /root/selinuxlab
      mode: 0755

  - name: Ensure SELinux test app service file is on the system
    ansible.builtin.copy:
      src: files/testapp.service
      dest: /root/selinuxlab/testapp.service
      mode: 0644

  - name: Compile the testapp
    ansible.builtin.shell:
      cmd: "make -f /root/selinuxlab/Makefile"
      chdir: /root/selinuxlab

  - name: Install the testapp
    ansible.builtin.shell:
      cmd: "make install -f /root/selinuxlab/Makefile"
      chdir: /root/selinuxlab

...
